Repository cclib/cclib, pull requests merged in 2018-09, with the labels that each got.

#583 docs: automatically update website on merge commit to master
  .travis.yml
  doc/sphinx/Makefile
  doc/sphinx/data_notes.rst
  requirements.txt
  travis/build_deploy_docs_manually.bash
  travis/build_docs.bash
  travis/deploy_docs_travis.bash
Labels: docs, maintenance

#609 docs: fix missing make target from #583
  .travis.yml
  doc/sphinx/Makefile
  travis/build_docs.bash
Labels: bug, docs

#608 Delete downloadwiki.py
  old/downloadwiki.py
Labels: maintenance

#614 Remove Gaussian03 unit test logfiles, and add regression tests
  data/Gaussian/basicGaussian03/CO_TD_delta.gjf
  data/Gaussian/basicGaussian03/CO_TD_delta.log
  data/Gaussian/basicGaussian03/C_bigbasis.gjf
  data/Gaussian/basicGaussian03/C_bigbasis.out
  data/Gaussian/basicGaussian03/Mo4OCl4-sp.com
  data/Gaussian/basicGaussian03/Mo4OCl4-sp.log
  data/Gaussian/basicGaussian03/dvb_gopt.gjf
  data/Gaussian/basicGaussian03/dvb_gopt.out
  data/Gaussian/basicGaussian03/dvb_ir.gjf
  data/Gaussian/basicGaussian03/dvb_ir.out
  data/Gaussian/basicGaussian03/dvb_raman.gjf
  data/Gaussian/basicGaussian03/dvb_raman.out
  data/Gaussian/basicGaussian03/dvb_sp.gjf
  data/Gaussian/basicGaussian03/dvb_sp.out
  data/Gaussian/basicGaussian03/dvb_sp_basis.gjf
  data/Gaussian/basicGaussian03/dvb_sp_basis.log
  data/Gaussian/basicGaussian03/dvb_sp_basis_b.gjf
  data/Gaussian/basicGaussian03/dvb_sp_basis_b.log
  data/Gaussian/basicGaussian03/dvb_td.gjf
  data/Gaussian/basicGaussian03/dvb_td.out
  data/Gaussian/basicGaussian03/dvb_un_sp.gjf
  data/Gaussian/basicGaussian03/dvb_un_sp.out
  data/Gaussian/basicGaussian03/dvb_un_sp_b.gjf
  data/Gaussian/basicGaussian03/dvb_un_sp_b.log
  data/Gaussian/basicGaussian03/metadata.txt
  data/Gaussian/basicGaussian03/water_ccd.com
  data/Gaussian/basicGaussian03/water_ccd.log
  data/Gaussian/basicGaussian03/water_ccsd(t).com
  data/Gaussian/basicGaussian03/water_ccsd(t).log
  data/Gaussian/basicGaussian03/water_ccsd.com
  data/Gaussian/basicGaussian03/water_ccsd.log
  data/Gaussian/basicGaussian03/water_cis.com
  data/Gaussian/basicGaussian03/water_cis.log
  data/Gaussian/basicGaussian03/water_cisd.com
  data/Gaussian/basicGaussian03/water_cisd.log
  data/Gaussian/basicGaussian03/water_mp2.com
  data/Gaussian/basicGaussian03/water_mp2.log
  data/Gaussian/basicGaussian03/water_mp3.com
  data/Gaussian/basicGaussian03/water_mp3.log
  data/Gaussian/basicGaussian03/water_mp4.com
  data/Gaussian/basicGaussian03/water_mp4.log
  data/Gaussian/basicGaussian03/water_mp4sdq.com
  data/Gaussian/basicGaussian03/water_mp4sdq.log
  data/Gaussian/basicGaussian03/water_mp5.com
  data/Gaussian/basicGaussian03/water_mp5.log
  test/method/testpopulation.py
  test/method/testvolume.py
  test/regression.py
  test/testdata
Labels: Gaussian, maintenance, regression, tests

#616 Changelog, docs and bump for v1.6
  ANNOUNCE
  CHANGELOG
  INSTALL
  cclib/__init__.py
  doc/sphinx/Makefile
  doc/sphinx/changelog.rst
  doc/sphinx/conf.py
  doc/sphinx/development.rst
  doc/sphinx/how_to_install.rst
  doc/sphinx/index.rst
  setup.py
Labels: maintenance

#622 Update DOI and Zenodo links for v1.6
  ANNOUNCE
  README.md
  doc/sphinx/index.rst
Labels: maintenance

#624 Merge release-1.6 branch into master
  ANNOUNCE
  CHANGELOG
  INSTALL
  README.md
  cclib/__init__.py
  doc/sphinx/Makefile
  doc/sphinx/changelog.rst
  doc/sphinx/conf.py
  doc/sphinx/development.rst
  doc/sphinx/how_to_install.rst
  doc/sphinx/index.rst
  setup.py
Labels: maintenance

#617 Start cleanup of CJSON-related methods
  cclib/io/ccio.py
  cclib/io/cjsonreader.py
  cclib/io/cjsonwriter.py
  cclib/parser/data.py
  cclib/scripts/ccwrite.py
  test/io/testcjsonreader.py
  test/io/testcjsonwriter.py
  test/regression.py
Labels: io

#525 Makes ORCA CASSCF parsing work for optimizations and open shells
  cclib/parser/orcaparser.py
Labels: ORCA, regression

#619 Alpha & beta electrons
  cclib/method/electrons.py
  test/method/testelectrons.py
  test/test_method.py
Labels: methods
