Repository cclib/cclib, pull requests merged in 2018-03, with the labels that each got.

#467 using requirements.txt in Travis CI
  .travis.yml
  requirements.txt
  travis/install_pyquante.sh
Labels: maintenance

#478 Fix links to docs (no tutorial anymore)
  ANNOUNCE
  INSTALL
  README.md
Labels: docs, maintenance

#466 fixed some typos in ccwrite
  src/cclib/io/ccio.py
  src/scripts/ccwrite
Labels: bug, io
