Repository cclib/cclib, pull requests merged in 2019-05, with the labels that each got.

#731 ORCA: make sure C_infv molecules have vibfreqs parsed properly
  test/regression.py
Labels: ORCA, regression

#728 Updates to the Travis CI configuration
  .travis.yml
Labels: maintenance

#716 Check for soft dependencies without importing them
  cclib/bridge/__init__.py
  cclib/bridge/cclib2biopython.py
  cclib/bridge/cclib2openbabel.py
  cclib/bridge/cclib2pyquante.py
  cclib/io/ccio.py
  cclib/io/cjsonwriter.py
  cclib/io/cmlwriter.py
  cclib/io/filewriter.py
  cclib/method/nuclear.py
  cclib/method/volume.py
  cclib/parser/utils.py
  cclib/scripts/ccframe.py
  requirements.txt
  setup.py
  test/io/testccio.py
  test/io/testscripts.py
Labels: maintenance

#712 Replace sys.argv/getopt/logic with argparse
  cclib/parser/molcasparser.py
  cclib/scripts/ccget.py
  cclib/scripts/cda.py
  test/regression.py
  test/test_data.py
  travis/run_unittest.bash
Labels: maintenance

#733 Move Psi3 to regression suite
  data/Psi3/basicPsi3/dvb_sp_hf.inp
  data/Psi3/basicPsi3/dvb_sp_hf.out
  doc/sphinx/coverage.py
  doc/sphinx/data.rst
  doc/sphinx/index.rst
  test/data/testSP.py
  test/regression.py
  test/test_data.py
  test/testdata
Labels: maintenance, parsers, regression

#729 Change the default loglevel to logging.ERROR
  cclib/parser/logfileparser.py
Labels: maintenance

#738 ORCA: add regression test
  test/regression.py
Labels: ORCA, regression

#730 Base file reader and writer classes should be abstract
  cclib/io/filereader.py
  cclib/io/filewriter.py
  test/io/testcjsonwriter.py
  test/io/testfilewriter.py
Labels: io

#743 Fix pytest not reporting test_data failures
  test/conftest.py
  test/data/testSP.py
  test/data/testSPun.py
  test/data/testTD.py
  test/test_data.py
  travis/run_pytest.bash
Labels: bug, maintenance, tests
