Repository cclib/cclib, pull requests merged in 2019-09, with the labels that each got.

#762 Fixes for moved GAMESS-US 2014 unit tests
  cclib/io/moldenwriter.py
  test/io/data/molden5.7_C_bigbasis.molden
  test/io/data/molden5.7_dvb_un_sp.molden
  test/io/data/molden5.7_water_mp2.molden
  test/io/testmoldenwriter.py
  test/io/testscripts.py
  test/testdata
Labels: GAMESS

#683 Travis CI: bump Python 3.6 -> 3.7
  .travis.yml
Labels: maintenance

#751 ORCA: handle all single-character delimiter lines for geometry opt
  cclib/parser/orcaparser.py
Labels: ORCA, regression

#749 Molden writer can now support ghost atoms.
  cclib/io/ccio.py
  cclib/io/filewriter.py
  cclib/io/moldenwriter.py
  cclib/scripts/ccwrite.py
  data/GAMESS/basicGAMESS-US2018/dvb_un_sp_ghost.dat
  data/GAMESS/basicGAMESS-US2018/dvb_un_sp_ghost.inp
  data/GAMESS/basicGAMESS-US2018/dvb_un_sp_ghost.out
  test/io/testmoldenwriter.py
Labels: feature, io

#741 Always keep the last etenergies and similar attributes
  cclib/parser/logfileparser.py
  cclib/parser/orcaparser.py
  test/regression.py
Labels: ORCA, bug

#768 Update changelist and bump version to v1.6.2
  ANNOUNCE
  CHANGELOG
  INSTALL
  doc/sphinx/Makefile
  doc/sphinx/changelog.rst
  doc/sphinx/conf.py
  doc/sphinx/development.rst
  doc/sphinx/how_to_install.rst
  doc/sphinx/index.rst
  setup.py
Labels: maintenance

#732 Metadata: full package versions
  cclib/parser/adfparser.py
  cclib/parser/daltonparser.py
  cclib/parser/gamessparser.py
  cclib/parser/gamessukparser.py
  cclib/parser/gaussianparser.py
  cclib/parser/jaguarparser.py
  cclib/parser/molcasparser.py
  cclib/parser/molproparser.py
  cclib/parser/mopacparser.py
  cclib/parser/nwchemparser.py
  cclib/parser/orcaparser.py
  cclib/parser/psi3parser.py
  cclib/parser/psi4parser.py
  cclib/parser/qchemparser.py
  cclib/parser/turbomoleparser.py
  requirements.txt
  setup.py
  test/data/testSP.py
  test/regression.py
Labels: parsers

#770 Make Logfile base class abstract
  cclib/parser/logfileparser.py
  cclib/parser/molcasparser.py
  cclib/parser/psi4parser.py
  cclib/parser/turbomoleparser.py
  doc/sphinx/data_notes.rst
  test/data/testSP.py
  test/parser/testlogfileparser.py
  test/parser/testspecificparsers.py
Labels: docs, parsers, tests

#771 Move float from Logfile static method to utils function
  cclib/parser/daltonparser.py
  cclib/parser/gamessukparser.py
  cclib/parser/gaussianparser.py
  cclib/parser/logfileparser.py
  cclib/parser/molcasparser.py
  cclib/parser/mopacparser.py
  cclib/parser/nwchemparser.py
  cclib/parser/orcaparser.py
  cclib/parser/qchemparser.py
  cclib/parser/turbomoleparser.py
  cclib/parser/utils.py
  test/parser/testlogfileparser.py
  test/test_utils.py
Labels: maintenance
