Repository cclib/cclib, pull requests merged in 2019-04, with the labels that each got.

#721 Making test/regressions.py PEP8 compliant
  test/regression.py
Labels: maintenance

#724 Handle existing comments for XYZ readers and writers
  cclib/io/xyzreader.py
  cclib/io/xyzwriter.py
  test/io/data/uracil_one_ref.xyz
  test/io/data/uracil_two_ref.xyz
  test/io/testxyzreader.py
Labels: io

#726 ORCA: fix for input file with embedding potentials
  cclib/parser/orcaparser.py
  test/regression.py
Labels: ORCA, regression
