Repository cclib/cclib, pull requests merged in 2020-10, with the labels that each got.

#954 Speed up `Volume.electrondensity_spin` and `Volume.wavefunction`
  cclib/method/volume.py
Labels: methods

#845 Adding a bridge module to the Atomic Simulation Environment (ASE)
  cclib/bridge/__init__.py
  cclib/bridge/cclib2ase.py
  requirements.txt
  test/bridge/h2o.traj
  test/bridge/testase.py
  test/test_bridge.py
Labels: bridge, feature

#958 Update docstrings and comments a bit
  cclib/method/hirshfeld.py
Labels: methods

#959 Update changelog and bump version to v1.6.4
  ANNOUNCE
  CHANGELOG
  INSTALL
  doc/sphinx/Makefile
  doc/sphinx/changelog.rst
  doc/sphinx/conf.py
  doc/sphinx/index.rst
  setup.py
Labels: maintenance

#961 Merge release-1.6.4 into master
  ANNOUNCE
  CHANGELOG
  INSTALL
  doc/sphinx/Makefile
  doc/sphinx/changelog.rst
  doc/sphinx/conf.py
  doc/sphinx/index.rst
  setup.py
Labels: maintenance

#963 Clean up scipy imports
  cclib/method/nuclear.py
  cclib/parser/utils.py
Labels: maintenance

#964 Raise ImportError when bridges are not available in unit tests
  test/bridge/testase.py
  test/bridge/testbiopython.py
  test/bridge/testhorton.py
  test/bridge/testpsi4.py
  test/bridge/testpyquante.py
  test/bridge/testpyscf.py
Labels: maintenance
