Repository cclib/cclib, pull requests merged in 2020-05, with the labels that each got.

#831 QChem: parse atomcoords in bohr
  cclib/parser/qchemparser.py
  test/regression.py
Labels: QChem, regression

#832 Test shape of ccenergies
  cclib/parser/daltonparser.py
  cclib/parser/nwchemparser.py
  cclib/parser/turbomoleparser.py
  test/data/testCC.py
  test/data/testMP.py
Labels: bug, tests

#853 [ORCA] Fix shape of ccenergies
  cclib/parser/orcaparser.py
Labels: ORCA

#854 Gaussian zpe
  cclib/parser/data.py
  cclib/parser/gaussianparser.py
  test/data/testvib.py
Labels: Gaussian, feature

#855 Fix invalid escape sequences by using raw strings
  cclib/io/ccio.py
  cclib/parser/gamessparser.py
  cclib/parser/gamessukparser.py
  cclib/parser/gaussianparser.py
  cclib/parser/jaguarparser.py
  cclib/parser/molcasparser.py
  cclib/parser/mopacparser.py
  cclib/parser/nwchemparser.py
  cclib/parser/orcaparser.py
  cclib/parser/qchemparser.py
  cclib/parser/turbomoleparser.py
  test/regression.py
Labels: maintenance

#856 Note about homos indexiness and more in parsing tutorial
  doc/sphinx/data_notes.rst
  doc/sphinx/how_to_parse.rst
Labels: docs

#858 Log last parsed line after encountering an exception during parsing
  cclib/parser/logfileparser.py
Labels: parsers

#857 [Gaussian] Revert 'Elmar Neumann' exception for which there is no regression
  cclib/parser/gaussianparser.py
Labels: Gaussian, regression

#865 [WIP] Try to fix travis
  requirements.txt
Labels: maintenance
