Repository cclib/cclib, pull requests merged in 2020-07, with the labels that each got.

#891 Fixes issue with dealing with reduced list of atoms
  cclib/parser/gaussianparser.py
Labels: Gaussian, bug

#894 Update pyquante bridge for pyquante2 support
  cclib/bridge/cclib2pyquante.py
  test/bridge/testpyquante.py
  test/test_bridge.py
  test/test_method.py
Labels: bridge

#888 Add docs for horton bridge
  doc/sphinx/bridge.rst
  doc/sphinx/contents.rst
  doc/sphinx/methods.rst
Labels: bridge, docs

#879 Add cclib --> horton 3 bridge, along with tests
  cclib/bridge/cclib2horton.py
  test/bridge/testhorton.py
  test/test_bridge.py
Labels: bridge

#896 Update volume method for updated cclib2pyquante bridge
  cclib/method/volume.py
  test/method/testvolume.py
  test/test_method.py
Labels: bridge, methods

#897 Add pyquante2 routines in volume method
  cclib/method/volume.py
  test/method/testvolume.py
  test/test_method.py
Labels: methods

#901 Change from numpy.nan to numpy.inf for printing full arrays
  cclib/scripts/ccget.py
Labels: bug

#898 Fix formula that determine number of grid points in volume function
  cclib/method/volume.py
Labels: bug, methods

#899 Update test routine for volume method to include verify data from each point on a grid
  cclib/method/volume.py
  data/Psi4/basicPsi4-1.2.1/water_mp2.in
  data/Psi4/basicPsi4-1.2.1/water_mp2.out
  test/method/testvolume.py
  test/method/water_mp2.cube
Labels: methods, tests

#825 Implement parsing T1 diagnostic
  cclib/parser/daltonparser.py
  cclib/parser/gamessparser.py
  cclib/parser/gaussianparser.py
  cclib/parser/molproparser.py
  cclib/parser/orcaparser.py
  cclib/parser/psi4parser.py
  cclib/parser/qchemparser.py
Labels: feature, parsers

#900 Add QTAIM method
  cclib/method/__init__.py
  cclib/method/bader.py
  cclib/method/volume.py
  test/method/testbader.py
  test/test_method.py
Labels: feature, methods

#907 Add the ability to use precalculated charge densities in Bader method
  cclib/method/bader.py
  cclib/method/volume.py
  test/method/testbader.py
  test/method/testvolume.py
Labels: feature, methods

#908 Ensure only converged excited state properties are reported in Gaussian parser
  cclib/parser/gaussianparser.py
  test/regression.py
Labels: Gaussian, regression

#903 Add docs for QTAIM method
  doc/sphinx/methods.rst
Labels: docs
