Repository cclib/cclib, pull requests merged in 2020-12, with the labels that each got.

#955 Print tracebacks by default when running regression tests
  test/regression.py
Labels: maintenance, tests

#953 New parser: formatted checkpoint files
  .gitignore
  cclib/io/ccio.py
  cclib/parser/__init__.py
  cclib/parser/fchkparser.py
  data/FChk/basicQChem5.2/MoOCl4_sp_modified.FChk
  data/FChk/basicQChem5.2/MoOCl4_sp_modified.in
  data/FChk/basicQChem5.2/MoOCl4_sp_modified.out
  data/FChk/basicQChem5.2/dvb_sp_modified.FChk
  data/FChk/basicQChem5.2/dvb_sp_modified.in
  data/FChk/basicQChem5.2/dvb_sp_modified.out
  data/FChk/basicQChem5.2/dvb_sp_un_modified.FChk
  data/FChk/basicQChem5.2/dvb_sp_un_modified.in
  data/FChk/basicQChem5.2/dvb_sp_un_modified.out
  test/data/testCore.py
  test/data/testSP.py
  test/data/testSPun.py
  test/regression.py
  test/test_data.py
  test/testdata
Labels: parsers

#989 XYZ writer: fix for no comment field in metadata
  cclib/io/xyzwriter.py
  test/io/testxyzwriter.py
Labels: bug, io

#990 Update changelog and bump version to v1.7
  ANNOUNCE
  CHANGELOG
  INSTALL
  cclib/__init__.py
  doc/sphinx/Makefile
  doc/sphinx/changelog.rst
  doc/sphinx/conf.py
  doc/sphinx/index.rst
  setup.py
Labels: maintenance
