Repository cclib/cclib, pull requests merged in 2020-08, with the labels that each got.

#872 Add Molpro 2018 unit tests but do not enable them
  data/Molpro/basicMolpro2018/C_bigbasis.com
  data/Molpro/basicMolpro2018/C_bigbasis.out
  data/Molpro/basicMolpro2018/C_bigbasis.xml
  data/Molpro/basicMolpro2018/Trp_polar.in
  data/Molpro/basicMolpro2018/Trp_polar.out
  data/Molpro/basicMolpro2018/Trp_polar.xml
  data/Molpro/basicMolpro2018/dvb_gopt.com
  data/Molpro/basicMolpro2018/dvb_gopt.log
  data/Molpro/basicMolpro2018/dvb_gopt.out
  data/Molpro/basicMolpro2018/dvb_gopt.xml
  data/Molpro/basicMolpro2018/dvb_ir.com
  data/Molpro/basicMolpro2018/dvb_ir.log
  data/Molpro/basicMolpro2018/dvb_ir.out
  data/Molpro/basicMolpro2018/dvb_ir.xml
  data/Molpro/basicMolpro2018/dvb_sphf.com
  data/Molpro/basicMolpro2018/dvb_sphf.out
  data/Molpro/basicMolpro2018/dvb_sphf.xml
  data/Molpro/basicMolpro2018/dvb_sphf_un.com
  data/Molpro/basicMolpro2018/dvb_sphf_un.out
  data/Molpro/basicMolpro2018/dvb_sphf_un.xml
  data/Molpro/basicMolpro2018/dvb_spks.com
  data/Molpro/basicMolpro2018/dvb_spks.out
  data/Molpro/basicMolpro2018/dvb_spks.xml
  data/Molpro/basicMolpro2018/h2o_ccd.com
  data/Molpro/basicMolpro2018/h2o_ccd.out
  data/Molpro/basicMolpro2018/h2o_ccd.xml
  data/Molpro/basicMolpro2018/h2o_ccsd.com
  data/Molpro/basicMolpro2018/h2o_ccsd.out
  data/Molpro/basicMolpro2018/h2o_ccsd.xml
  data/Molpro/basicMolpro2018/h2o_ccsdt.com
  data/Molpro/basicMolpro2018/h2o_ccsdt.out
  data/Molpro/basicMolpro2018/h2o_ccsdt.xml
  data/Molpro/basicMolpro2018/h2o_mp2.com
  data/Molpro/basicMolpro2018/h2o_mp2.out
  data/Molpro/basicMolpro2018/h2o_mp2.xml
  data/Molpro/basicMolpro2018/h2o_mp3.com
  data/Molpro/basicMolpro2018/h2o_mp3.out
  data/Molpro/basicMolpro2018/h2o_mp3.xml
  data/Molpro/basicMolpro2018/h2o_mp4.com
  data/Molpro/basicMolpro2018/h2o_mp4.out
  data/Molpro/basicMolpro2018/h2o_mp4.xml
Labels: Molpro

#745 Parse empirical dispersion corrections
  cclib/parser/daltonparser.py
  cclib/parser/data.py
  cclib/parser/gamessparser.py
  cclib/parser/gaussianparser.py
  cclib/parser/molproparser.py
  cclib/parser/nwchemparser.py
  cclib/parser/orcaparser.py
  cclib/parser/psi4parser.py
  cclib/parser/qchemparser.py
  cclib/parser/utils.py
  data/DALTON/basicDALTON-2018/dvb_dispersion_bp86_d3zero.dal
  data/DALTON/basicDALTON-2018/dvb_dispersion_bp86_d3zero.out
  data/GAMESS/basicFirefly8.1/dvb_dispersion_bp86_d3zero.inp
  data/GAMESS/basicFirefly8.1/dvb_dispersion_bp86_d3zero.out
  data/GAMESS/basicGAMESS-US2018/dvb_dispersion_bp86_d3zero.dat
  data/GAMESS/basicGAMESS-US2018/dvb_dispersion_bp86_d3zero.inp
  data/GAMESS/basicGAMESS-US2018/dvb_dispersion_bp86_d3zero.out
  data/Gaussian/basicGaussian09/dvb_dispersion_bp86_d3zero.in
  data/Gaussian/basicGaussian09/dvb_dispersion_bp86_d3zero.out
  data/Gaussian/basicGaussian16/dvb_dispersion_bp86_d3zero.in
  data/Gaussian/basicGaussian16/dvb_dispersion_bp86_d3zero.out
  data/Molpro/basicMolpro2018/dvb_dispersion_bp86_d3zero.in
  data/Molpro/basicMolpro2018/dvb_dispersion_bp86_d3zero.out
  data/Molpro/basicMolpro2018/dvb_dispersion_bp86_d3zero.xml
  data/NWChem/basicNWChem6.8/dvb_dispersion_bp86_d3zero.in
  data/NWChem/basicNWChem6.8/dvb_dispersion_bp86_d3zero.out
  data/ORCA/basicORCA4.1/dvb_dispersion_bp86_d3zero.in
  data/ORCA/basicORCA4.1/dvb_dispersion_bp86_d3zero.out
  data/ORCA/basicORCA4.2/dvb_dispersion_bp86_d3zero.in
  data/ORCA/basicORCA4.2/dvb_dispersion_bp86_d3zero.out
  data/Psi4/basicPsi4-1.2.1/dvb_dispersion_bp86_d3zero.in
  data/Psi4/basicPsi4-1.2.1/dvb_dispersion_bp86_d3zero.out
  data/Psi4/basicPsi4-1.3.1/dvb_dispersion_bp86_d3zero.in
  data/Psi4/basicPsi4-1.3.1/dvb_dispersion_bp86_d3zero.out
  data/QChem/basicQChem5.1/dvb_dispersion_bp86_d3zero.in
  data/QChem/basicQChem5.1/dvb_dispersion_bp86_d3zero.out
  test/data/testSP.py
  test/testdata
Labels: ORCA, feature, parsers

#914 Add a function to read in proatom densities from chargemol's atomic_densities
  .gitignore
  .travis.yml
  cclib/method/__init__.py
  cclib/method/ddec.py
  test/method/atoms.h5
  test/method/testddec.py
  test/test_method.py
Labels: methods

#917 Add optional weight argument for integrate method in volume
  cclib/method/bader.py
  cclib/method/volume.py
Labels: methods

#916 Calculate step 2 reference ion charge value of DDEC6
  cclib/method/ddec.py
  test/method/testddec.py
Labels: methods

#919 Add a function that conditions reference density in DDEC6
  cclib/method/ddec.py
  cclib/method/volume.py
  test/method/testddec.py
Labels: methods

#920 Calculate weights assigned to each grid point in DDEC6
  cclib/method/ddec.py
  test/method/testddec.py
Labels: methods

#921 Add function that evaluates G_A(r_A) and H_A(r_A) for DDEC6
  cclib/method/ddec.py
  test/method/testddec.py
Labels: methods

#926 Add docs for DDEC6
  doc/sphinx/methods.rst
Labels: docs, methods

#927 Separate out Hirshfeld method from DDEC6 as a standalone method
  cclib/method/__init__.py
  cclib/method/ddec.py
  cclib/method/hirshfeld.py
  cclib/method/stockholder.py
  test/method/testhirshfeld.py
  test/test_method.py
Labels: maintenance, methods

#928 Add docs for Hirshfeld method
  cclib/method/ddec.py
  doc/sphinx/methods.rst
Labels: docs, methods

#930 Clean up DDEC6 code
  cclib/method/ddec.py
  test/method/testddec.py
Labels: maintenance, methods
