Repository cclib/cclib, pull requests merged in 2020-09, with the labels that each got.

#934 Add a footnote in docs for DDEC6/Hirshfeld about proatom density generation
  cclib/method/ddec.py
  doc/sphinx/methods.rst
  test/method/generate_proatom.sh
  test/method/template.in
Labels: docs

#940 Fix a typo in DDEC
  cclib/method/ddec.py
Labels: bug, methods

#938 Fix a typo in Bader method
  cclib/method/bader.py
Labels: bug, methods

#932 Remove explicit indexing from DDEC6
  cclib/method/ddec.py
Labels: maintenance, methods

#923 Add vibrational reduced masses and force constants to parse data
  cclib/parser/data.py
  cclib/parser/gamessparser.py
  cclib/parser/gaussianparser.py
  cclib/parser/jaguarparser.py
  cclib/parser/molcasparser.py
  cclib/parser/mopacparser.py
  cclib/parser/psi4parser.py
  cclib/parser/qchemparser.py
  cclib/parser/turbomoleparser.py
  cclib/parser/utils.py
  doc/sphinx/data_notes.rst
  test/data/testvib.py
  test/testdata
Labels: feature, parsers

#951 ORCA: constrained geom opt has an extra line before gradients
  cclib/parser/orcaparser.py
  test/regression.py
Labels: ORCA, regression

#943 Fixing bug with two letter chemical symbols
  cclib/parser/qchemparser.py
  test/regression.py
Labels: QChem, bug

#944 convert Gaussian's grads from input oriantion to standard orientation
  cclib/parser/gaussianparser.py
  cclib/parser/utils.py
  doc/sphinx/data_notes.rst
  test/data/testGeoOpt.py
  test/test_utils.py
  test/testdata
Labels: Gaussian, parsers

#945 Fix handling of open shell systems in moldenwriter and wfxwriter
  cclib/io/moldenwriter.py
  cclib/io/wfxwriter.py
  test/regression.py
Labels: bug, io
