Repository cclib/cclib, pull requests merged in 2021-09, with the labels that each got.

#1069 Update changelog and bump version to v.1.7.1
  ANNOUNCE
  CHANGELOG
  INSTALL
  cclib/__init__.py
  doc/sphinx/Makefile
  doc/sphinx/changelog.rst
  doc/sphinx/conf.py
  doc/sphinx/index.rst
  setup.py
Labels: maintenance

#1066 Fix Sphinx warnings about too-short underlines
  doc/sphinx/data_notes.rst
  doc/sphinx/methods.rst
Labels: maintenance, docs

#1073 Merge release 1.7.1 into master
  ANNOUNCE
  CHANGELOG
  INSTALL
  cclib/__init__.py
  doc/sphinx/Makefile
  doc/sphinx/changelog.rst
  doc/sphinx/conf.py
  doc/sphinx/index.rst
  setup.py
Labels: maintenance

#1074 Tweaks to docs needed after v1.7.1
  doc/sphinx/conf.py
  doc/sphinx/coverage.py
Labels: docs

#1057 NWChem Excited states, Vibrational Frequencies and Thermochimistry
  cclib/parser/nwchemparser.py
  data/NWChem/basicNWChem7.0/dvb_ir.nw
  data/NWChem/basicNWChem7.0/dvb_ir.out
  data/NWChem/basicNWChem7.0/dvb_td.nw
  data/NWChem/basicNWChem7.0/dvb_td.out
  test/data/testTD.py
  test/data/testvib.py
  test/regression.py
  test/testdata
Labels: parsers, ORCA
