Repository cclib/cclib, pull requests merged in 2021-01, with the labels that each got.

#994 Merge release 1.7 back into master
  ANNOUNCE
  CHANGELOG
  INSTALL
  cclib/__init__.py
  doc/sphinx/Makefile
  doc/sphinx/changelog.rst
  doc/sphinx/conf.py
  doc/sphinx/index.rst
  setup.py
Labels: maintenance

#992 Fix GAMESS parser when there are >100 scf iterations
  cclib/parser/gamessparser.py
  test/regression.py
Labels: GAMESS, regression

#996 Dynamically set attribute and coverage column widths
  doc/sphinx/Makefile
  doc/sphinx/_static/increase_max_width.css
  doc/sphinx/attributes.py
  doc/sphinx/conf.py
  doc/sphinx/coverage.py
Labels: docs

#999 Update Zenodo badge to new DOI
  README.md
Labels: maintenance

#1000 Update DOI in ANNOUNCE, and add Shiv and Geoffrey to Zenodo ref
  ANNOUNCE
Labels: maintenance
