Repository cclib/cclib, pull requests merged in 2022-02, with the labels that each got.

#1086 Pytest filter through GitHub actions
  .github/scripts/run_pytest.bash
  .github/scripts/run_pytest_methods.bash
  .github/workflows/cclib_pytest.yml
Labels: tests

#1099 super calls don't require arguments in Python 3
  cclib/io/cjsonreader.py
  cclib/io/cjsonwriter.py
  cclib/io/cmlwriter.py
  cclib/io/xyzreader.py
  cclib/io/xyzwriter.py
  cclib/method/bader.py
  cclib/method/bickelhaupt.py
  cclib/method/cda.py
  cclib/method/cspa.py
  cclib/method/ddec.py
  cclib/method/density.py
  cclib/method/electrons.py
  cclib/method/fragments.py
  cclib/method/hirshfeld.py
  cclib/method/lpa.py
  cclib/method/mbo.py
  cclib/method/moments.py
  cclib/method/mpa.py
  cclib/method/nuclear.py
  cclib/method/opa.py
  cclib/method/orbitals.py
  cclib/method/population.py
  cclib/method/stockholder.py
  cclib/parser/adfparser.py
  cclib/parser/daltonparser.py
  cclib/parser/data.py
  cclib/parser/fchkparser.py
  cclib/parser/gamessparser.py
  cclib/parser/gamessukparser.py
  cclib/parser/gaussianparser.py
  cclib/parser/jaguarparser.py
  cclib/parser/molcasparser.py
  cclib/parser/molproparser.py
  cclib/parser/mopacparser.py
  cclib/parser/nwchemparser.py
  cclib/parser/orcaparser.py
  cclib/parser/psi3parser.py
  cclib/parser/psi4parser.py
  cclib/parser/qchemparser.py
  cclib/parser/turbomoleparser.py
Labels: maintenance

#1089 Add point group detection, part 2
  cclib/parser/adfparser.py
  cclib/parser/gamessparser.py
  cclib/parser/gamessukparser.py
  cclib/parser/gaussianparser.py
  cclib/parser/jaguarparser.py
  cclib/parser/molproparser.py
  cclib/parser/nwchemparser.py
  cclib/parser/orcaparser.py
  cclib/parser/psi3parser.py
  cclib/parser/psi4parser.py
  cclib/parser/qchemparser.py
  test/data/testSP.py
  test/regression.py
Labels: feature, parsers

#1106 Added two if statements to check for PATH and List of PATH
  cclib/io/ccio.py
Labels: maintenance

#1107 Update mailing list link to Google Groups
  doc/sphinx/index.rst
Labels: maintenance
