Repository cclib/cclib, pull requests merged in 2022-11, with the labels that each got.

#1158 documentation build fixes
  doc/sphinx/bridge.rst
  doc/sphinx/data_notes.rst
Labels: maintenance, docs

#1157 Remove Python 2 leftovers
  test/bridge/testhorton.py
  test/bridge/testpyquante.py
  test/test_bridge.py
Labels: maintenance, tests

#1162 Gauss mocoeff
  cclib/parser/gaussianparser.py
Labels: Gaussian
