Repository cclib/cclib, pull requests merged in 2022-03, with the labels that each got.

#1115 Update README.md with the Google Groups link
  README.md
Labels: maintenance

#1111 Gaussian C.01 CC Fix
  cclib/parser/gaussianparser.py
  test/regression.py
Labels: Gaussian, regression

#1117 FChk: fix units for parsing MO energies
  cclib/parser/fchkparser.py
  test/data/testSP.py
  test/regression.py
  test/testdata
Labels: regression, fchk

#1104 Add dispersion energies notes to documentation
  cclib/parser/data.py
  doc/sphinx/data_notes.rst
Labels: docs

#1119 Update development.rst
  doc/sphinx/development.rst
Labels: docs
