Repository cclib/cclib, pull requests merged in 2023-08, with the labels that each got.

#1236 makeopenbabel: atomcoords or atomnos can be optional
  cclib/bridge/cclib2openbabel.py
  cclib/io/filewriter.py
  test/bridge/testopenbabel.py
Labels: bridge

#1242 Add nuclear repulsion energy to docs
  doc/sphinx/methods.rst
Labels: methods, docs

#1237 DALTON: more general parsing of atomcoords
  cclib/parser/daltonparser.py
  test/data/testBasis.py
Labels: bug, Dalton

#1240 Gaussian: move formatted checkpoint files to testing directory
  cclib/bridge/cclib2horton.py
  cclib/parser/fchkparser.py
  data/FChk/basicGaussian09/CO_TD_delta.fchk
  data/FChk/basicGaussian09/C_bigbasis.fchk
  data/FChk/basicGaussian09/Mo4OCl4-sp.fchk
  data/FChk/basicGaussian09/Trp_polar.fchk
  data/FChk/basicGaussian09/dvb_gopt.fchk
  data/FChk/basicGaussian09/dvb_ir.fchk
  data/FChk/basicGaussian09/dvb_raman.fchk
  data/FChk/basicGaussian09/dvb_scan.fchk
  data/FChk/basicGaussian09/dvb_sp.fchk
  data/FChk/basicGaussian09/dvb_td.fchk
  data/FChk/basicGaussian09/dvb_un_sp.fchk
  data/FChk/basicGaussian09/dvb_un_sp_b.fchk
  data/FChk/basicGaussian09/water_ccd.fchk
  data/FChk/basicGaussian09/water_ccsd.fchk
  data/FChk/basicGaussian09/water_ccsdt.fchk
  data/FChk/basicGaussian09/water_cis.fchk
  data/FChk/basicGaussian09/water_cisd.fchk
  data/FChk/basicGaussian09/water_mp2.fchk
  data/FChk/basicGaussian09/water_mp3.fchk
  data/FChk/basicGaussian09/water_mp4.fchk
  data/FChk/basicGaussian09/water_mp4sdq.fchk
  data/FChk/basicGaussian09/water_mp5.fchk
  data/FChk/basicGaussian16/CO_TD_delta.fchk
  data/FChk/basicGaussian16/C_bigbasis.fchk
  data/FChk/basicGaussian16/Mo4OCl4-sp.fchk
  data/FChk/basicGaussian16/Trp_polar.fchk
  data/FChk/basicGaussian16/dvb_gopt.fchk
  data/FChk/basicGaussian16/dvb_ir.fchk
  data/FChk/basicGaussian16/dvb_raman.fchk
  data/FChk/basicGaussian16/dvb_scan_relaxed.fchk
  data/FChk/basicGaussian16/dvb_scan_unrelaxed.fchk
  data/FChk/basicGaussian16/dvb_sp.fchk
  data/FChk/basicGaussian16/dvb_sp_no.fchk
  data/FChk/basicGaussian16/dvb_td.gjf
  data/FChk/basicGaussian16/dvb_td.out
  data/FChk/basicGaussian16/dvb_un_sp.fchk
  data/FChk/basicGaussian16/dvb_un_sp_b.fchk
  data/FChk/basicGaussian16/dvb_un_sp_nso.fchk
  data/FChk/basicGaussian16/water_ccd.fchk
  data/FChk/basicGaussian16/water_ccsd.fchk
  data/FChk/basicGaussian16/water_ccsdt.fchk
  data/FChk/basicGaussian16/water_cis.fchk
  data/FChk/basicGaussian16/water_cisd.fchk
  data/FChk/basicGaussian16/water_mp2.fchk
  data/FChk/basicGaussian16/water_mp3.fchk
  data/FChk/basicGaussian16/water_mp4.fchk
  data/FChk/basicGaussian16/water_mp4sdq.fchk
  data/FChk/basicGaussian16/water_mp5.fchk
  data/Gaussian/basicGaussian16/dvb_td.fchk
  test/bridge/testhorton.py
  test/data/testSP.py
  test/data/testTD.py
  test/data/testvib.py
  test/io/testccio.py
  test/testdata
Labels: tests, fchk

#1244 NBO Parser: Mapping extracted values to attributes
  cclib/parser/nboparser.py
Labels: parsers, NBO

#1243 Output nuclear repulsion energy in eV
  cclib/method/nuclear.py
  test/method/testnuclear.py
Labels: bug, methods

#1238 Improve detection of XYZ files, fix calling fallback mechanism
  .github/scripts/run_pytest.bash
  .github/scripts/run_unittest.bash
  cclib/io/ccio.py
  test/regression_io.py
Labels: regression, io

#1252 Update ANNOUNCE for v1.8
  ANNOUNCE
Labels: maintenance

#1253 docs: update maintainers list and parsed program versions
  doc/sphinx/development.rst
  doc/sphinx/index.rst
  doc/sphinx/methods.rst
Labels: maintenance, docs

#1250 Update changelog and bump version to v1.8
  CHANGELOG
  THANKS
  cclib/__init__.py
  doc/sphinx/Makefile
  doc/sphinx/changelog.rst
  doc/sphinx/conf.py
  doc/sphinx/how_to_install.rst
  doc/sphinx/index.rst
  manifest.py
  setup.py
Labels: maintenance

#1260 Remove outdated listings of supported parsers from docstrings
  cclib/__init__.py
  cclib/parser/__init__.py
  cclib/parser/logfileparser.py
Labels: maintenance

#1258 Add attribute _dictofdicts
  cclib/parser/data.py
  test/parser/testdata.py
Labels: maintenance

#1262 Add sphinx_rtd_theme as dev dependency
  requirements.txt
Labels: maintenance

#1265 Merge release 1.8 branch back into master
  ANNOUNCE
  CHANGELOG
  README.md
  THANKS
  cclib/__init__.py
  cclib/parser/__init__.py
  cclib/parser/logfileparser.py
  cclib/parser/utils.py
  doc/sphinx/Makefile
  doc/sphinx/changelog.rst
  doc/sphinx/conf.py
  doc/sphinx/development.rst
  doc/sphinx/how_to_install.rst
  doc/sphinx/index.rst
  doc/sphinx/methods.rst
  manifest.py
  setup.py
Labels: maintenance

#1263 Remove obsolete hacks for silencing pyquante2/Cython problems in docs build
  doc/sphinx/Makefile
Labels: maintenance

#1251 Create and test new attributes for the NBO parser
  .readthedocs.yml
  cclib/io/ccio.py
  cclib/parser/data.py
  cclib/parser/nboparser.py
  test/data/testSP.py
  test/regression.py
  test/test_data.py
  test/testdata
Labels: NBO
