Repository cclib/cclib, pull requests merged in 2024-03, with the labels that each got.

#1374 switch to release-1.8.1 branch for regressions
  data/regression_download.sh
Labels: maintenance

#1373 Calculate version from tags and `versioningit`
  .github/workflows/cclib_docs_push.yml
  .github/workflows/cclib_pytest.yml
  .gitignore
  MANIFEST.in
  cclib/__init__.py
  manifest.py
  pyproject.toml
  tools/versioningit_override.py
Labels: maintenance

#1363 Push to PyPI on tag
  .github/workflows/ci.yml
  .github/workflows/publish.yml
  .github/workflows/test_and_package.yml
  README.md
Labels: maintenance

#1375 ignore pre-commit autofix commits in git blame
  .git-blame-ignore-revs
Labels: maintenance

#1367 Nix-Builds
  .envrc
  .github/workflows/cclib_nix.yml
  .gitignore
  flake.lock
  flake.nix
  nix/cclib.nix
  nix/overlay.nix
Labels: feature, maintenance

#1355 Add and update developer guidelines
  .pre-commit-config.yaml
  ANNOUNCE
  THANKS
  doc/sphinx/bridge.rst
  doc/sphinx/changelog.rst
  doc/sphinx/data_notes.rst
  doc/sphinx/development.rst
  doc/sphinx/how_to_install.rst
  doc/sphinx/how_to_parse.rst
  doc/sphinx/methods.rst
Labels: maintenance, docs

#1382 Remove URL-based requirements
  pyproject.toml
  requirements-dev.txt
Labels: maintenance

#1387 More changelog updates for 1.8.1
  doc/sphinx/changelog.rst
  doc/sphinx/helpers/README.md
  doc/sphinx/helpers/milestone_issues_and_prs.py
Labels: maintenance, docs

#1388 Fix CI badge in README
  README.md
Labels: maintenance

#1396 Changes to main-rebase-merges
  cclib/method/volume.py
Labels: maintenance
