Repository cclib/cclib, pull requests merged in 2024-08, with the labels that each got.

#1461 Add citation details for new paper
  README.md
  doc/sphinx/index.rst
Labels: docs

#1463 Fix parsing of elements in xtb parser
  cclib/parser/xtbparser.py
Labels: bug, xTB

#1443 Apply pyupgrade and fix ruff lints
  .pre-commit-config.yaml
  cclib/__init__.py
  cclib/bridge/__init__.py
  cclib/bridge/cclib2openbabel.py
  cclib/bridge/cclib2psi4.py
  cclib/bridge/cclib2pyscf.py
  cclib/io/__init__.py
  cclib/io/ccio.py
  cclib/io/filewriter.py
  cclib/io/moldenwriter.py
  cclib/io/wfxwriter.py
  cclib/method/__init__.py
  cclib/method/calculationmethod.py
  cclib/method/cda.py
  cclib/method/cspa.py
  cclib/method/ddec.py
  cclib/method/electrons.py
  cclib/method/fragments.py
  cclib/method/hirshfeld.py
  cclib/method/moments.py
  cclib/method/nuclear.py
  cclib/method/opa.py
  cclib/method/population.py
  cclib/method/volume.py
  cclib/parser/__init__.py
  cclib/parser/adfparser.py
  cclib/parser/daltonparser.py
  cclib/parser/data.py
  cclib/parser/fchkparser.py
  cclib/parser/gamessdatparser.py
  cclib/parser/gamessparser.py
  cclib/parser/gamessukparser.py
  cclib/parser/gaussianparser.py
  cclib/parser/jaguarparser.py
  cclib/parser/logfileparser.py
  cclib/parser/logfilewrapper.py
  cclib/parser/molcasparser.py
  cclib/parser/molproparser.py
  cclib/parser/mopacparser.py
  cclib/parser/nboparser.py
  cclib/parser/nwchemparser.py
  cclib/parser/orcaparser.py
  cclib/parser/psi4parser.py
  cclib/parser/qchemparser.py
  cclib/parser/turbomoleparser.py
  cclib/parser/utils.py
  cclib/progress/__init__.py
  cclib/scripts/__init__.py
  doc/sphinx/conf.py
  pyproject.toml
  test/__init__.py
  test/bridge/testopenbabel.py
  test/data/testMP.py
  test/data/testNMR.py
  test/method/testddec.py
  test/method/testhirshfeld.py
  test/method/testvolume.py
  test/parser/testlogfileparser.py
  test/regression.py
Labels: maintenance

#1467 Fix Nix build and add to CI
  .github/workflows/nix.yml
  nix/cclib.nix
  pyproject.toml
Labels: maintenance, continuous-integration

#1474 Don't run nix build in CI
  .github/workflows/nix.yml
Labels: maintenance, continuous-integration
