Repository cclib/cclib, pull requests merged in 2024-01, with the labels that each got.

#1338 regression: remove skip on testQChem_QChem5_1_old_final_print_1_out
  test/regression.py
Labels: tests, QChem

#1344 unpin pyscf and biopython optional dependencies
  pyproject.toml
  test/bridge/testpyscf.py
Labels: maintenance, tests, bridge

#1309 Replace `unittest` with `pytest` for `testdata` and regressions
  .github/scripts/run_pytest.bash
  .github/scripts/run_pytest_methods.bash
  .github/scripts/run_unittest.bash
  .github/workflows/cclib_pytest.yml
  cclib/scripts/__init__.py
  cclib/scripts/ccframe.py
  doc/sphinx/Makefile
  doc/sphinx/coverage.py
  pyproject.toml
  pytest.ini
  test/bridge/testbiopython.py
  test/bridge/testhorton.py
  test/bridge/testopenbabel.py
  test/bridge/testpyquante.py
  test/bridge/testpyscf.py
  test/conftest.py
  test/data/skip.py
  test/data/testBOMD.py
  test/data/testBasis.py
  test/data/testCC.py
  test/data/testCI.py
  test/data/testCore.py
  test/data/testGeoOpt.py
  test/data/testMP.py
  test/data/testNMR.py
  test/data/testPolar.py
  test/data/testSP.py
  test/data/testSPun.py
  test/data/testScan.py
  test/data/testTD.py
  test/data/testTDun.py
  test/data/testvib.py
  test/io/testccio.py
  test/io/testfilewriter.py
  test/io/testmoldenwriter.py
  test/io/testscripts.py
  test/method/testddec.py
  test/method/testhirshfeld.py
  test/method/testnuclear.py
  test/method/testorbitals.py
  test/parser/testdata.py
  test/parser/testutils.py
  test/regression.py
  test/test_bridge.py
  test/test_data.py
  test/test_io.py
  test/test_method.py
  test/test_parser.py
  test/test_utils.py
  test/testall.py
  test/testdata
Labels: maintenance, tests

#1346 Continue removing `unittest`
  .github/workflows/cclib_docs_push.yml
  .github/workflows/cclib_pytest.yml
  cclib/parser/molproparser.py
  cclib/parser/orcaparser.py
  test/bridge/testase.py
  test/bridge/testpsi4.py
  test/bridge/testpyscf.py
  test/data/testCC.py
  test/data/testCI.py
  test/data/testGeoOpt.py
  test/data/testMP.py
  test/data/testSP.py
  test/data/testSPun.py
  test/io/testcjsonreader.py
  test/io/testcjsonwriter.py
  test/io/testfilewriter.py
  test/io/testmoldenwriter.py
  test/io/testwfxwriter.py
  test/io/testxyzreader.py
  test/io/testxyzwriter.py
  test/method/testbader.py
  test/method/testcda.py
  test/method/testcm5.py
  test/method/testelectrons.py
  test/method/testmbo.py
  test/method/testmoments.py
  test/method/testnuclear.py
  test/method/testpopulation.py
  test/method/testvolume.py
  test/parser/testlogfileparser.py
  test/parser/testspecificparsers.py
  test/regression_io.py
Labels: maintenance, tests

#1351 Update version to 1.8.1
  cclib/__init__.py
  doc/sphinx/Makefile
  doc/sphinx/conf.py
  doc/sphinx/how_to_install.rst
  pyproject.toml
Labels: maintenance

#1354 issue regarding the optdone boolean and list convergence resolved
  cclib/parser/data.py
Labels: maintenance, docs

#1352 Update CHANGELOG for 1.8.1
  CHANGELOG
  THANKS
  doc/sphinx/changelog.rst
  doc/sphinx/helpers/.gitignore
  doc/sphinx/helpers/github_graphql_query.py
  doc/sphinx/helpers/milestone_issues_and_prs.graphql
  doc/sphinx/helpers/milestone_issues_and_prs.py
Labels: maintenance, docs

#1357 fix population method tests for switch from unittest to pytest
  .github/workflows/cclib_pytest.yml
  cclib/method/bader.py
  cclib/method/ddec.py
  test/method/testbader.py
  test/method/testpopulation.py
Labels: maintenance, tests
