Repository cclib/cclib, pull requests merged in 2024-06, with the labels that each got.

#1436 update pyquante2 install location
  requirements-dev.txt
Labels: maintenance

#1433 Hotfix for missing pybel when openbabel is available
  cclib/io/ccio.py
  cclib/io/filewriter.py
Labels: bridge

#1427 Additional psi4 attributes for v2
  cclib/attribute_parsers/__init__.py
  cclib/attribute_parsers/atombasis.py
  cclib/attribute_parsers/atomcharges.py
  cclib/attribute_parsers/atommasses.py
  cclib/attribute_parsers/atomnos.py
  cclib/attribute_parsers/ccenergies.py
  cclib/attribute_parsers/dispersionenergies.py
  cclib/attribute_parsers/gbasis.py
  cclib/attribute_parsers/geotargets.py
  cclib/attribute_parsers/scftargets.py
  cclib/combinator/combinator.py
  pytest.ini
  test/data/testCC.py
  test/data/testSP.py
  test/testdata
Labels: Psi

#1445 unpin versioningit upper bound
  .github/workflows/test_and_package.yml
  cclib/bridge/cclib2openbabel.py
  pyproject.toml
Labels: maintenance

#1449 enforce FileWrappers as iterators over strings
  cclib/parser/logfilewrapper.py
Labels: maintenance
