Repository cclib/cclib, pull requests merged in 2025-02, with the labels that each got.

#1519 add NWChem 7.2.3 Mulliken charges
  cclib/parser/nwchemparser.py
  test/regression.py
Labels: NWChem, regression

#1532 docs: clarify how to add files for new program versions
  doc/sphinx/development.rst
  doc/sphinx/how_to_install.rst
Labels: maintenance, docs

#1535 Switch from Dependabot to Renovate
  .github/dependabot.yml
  renovate.json
Labels: maintenance
